javavulnlab:
  image: m4n3dw0lf/javavulnerablelab
  ports:
    - 8080:8080
  links:
    - mysql

dvwa:
  image: m4n3dw0lf/docker-vulnerable-dvwa
  ports:
    - 80:80
  links:
    - mysql

dsvw:
  image: m4n3dw0lf/dsvw
  ports:
    - 8081:8081

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
